name: gaming4free renew (WARP + Python)

on:
  push:                # 新增这行，以后只要您修改代码，它就会立刻自动跑一次
  workflow_dispatch:
  schedule:
    - cron: "35 * * * *"   # 稍微改一下数字，比如改成 45

jobs:
  renew-server:
    # 💥 核心绝杀：强行切换为微软官方的 Windows 真实环境！
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        # Windows 下直接 pip install，再也不需要装虚拟显示器了
        run: pip install seleniumbase

      - name: Run Auto Renew Script
        env:
          PROXY_URL: ${{ secrets.PROXY_URL }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        # 💥 核心绝杀：直接干干净净地跑 python，删掉原来那个坑人的 xvfb-run -a
        run: python renew.py
